# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{liquibase-rails}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tal Rotbart"]
  s.date = %q{2009-09-08}
  s.description = %q{Liquibase drop-in replacement tasks for Rails migrations}
  s.email = %q{redbeard@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "lib/jar/lgpl.txt",
     "lib/jar/liquibase",
     "lib/jar/liquibase-1.9.1.jar",
     "lib/jar/liquibase.bat",
     "lib/liquibase-rails.rb",
     "lib/liquibase/liquibase.rb"
  ]
  s.homepage = %q{http://github.com/redbeard/liquibase-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{liquibase-rails}
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{Liquibase drop-in replacement tasks for Rails migrations}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
